### ISSUE TITLE
It throws an exception on Safari 13.1.2

### ISSUE THREAD

**Issue by heymcbain** [qonto/ember-lottie#272]
When used on older versions of Safari this package throws TypeError: `this.mediaQuery?.addEventListener is not a function`. 

This could be potentially fixed by using deprecated APIs if newer APIs are not available: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener

**Comment by nicolasgasco** [comment]
@vscav I'm having a look at the Sentry report and the error was triggered by Safari 13.
I see that both `matchMedia` and `addEventListener` are well supported.

Do you think this could really be a support issue or that maybe we should look elsewhere?

![Screenshot 2023-11-09 at 15 35 39](https://github.com/qonto/ember-lottie/assets/73175085/dba0e355-c71c-46b4-9576-893aa9cd144f)
![Screenshot 2023-11-09 at 15 35 46](https://github.com/qonto/ember-lottie/assets/73175085/10aadf66-a55b-4745-abac-e2b447727ffd)

**Comment by nicolasgasco** [comment]
This seems to be related to a known issue: `MediaQueryList.addEventListener` does not work in Safari (see https://caniuse.com/?search=matchmedia)
![Screenshot 2023-11-09 at 15 37 17](https://github.com/qonto/ember-lottie/assets/73175085/f6338b24-0294-43de-95f5-18cdb94fe78a)

**Comment by nicolasgasco** [comment]
Hi, @heymcbain and @vscav ! A fix to this issue was proposed here: https://github.com/qonto/ember-lottie/pull/273. Would you mind having a look at it?
